apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  namespace: echo-server-two
spec:
  containers:
    - name: echo-server
      image: ealen/echo-server
      envFrom:
        - secretRef:
            name: echo-server-secrets
