apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  namespace: echo-server
spec:
  containers:
    - name: echo-server
      image: ealen/echo-server
      ports:
        - name: http
          containerPort: 80
  restartPolicy: Always
