apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-example
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned
  dnsNames:
    - example.com
    - www.example.com
  secretName: selfsigned-example-tls
