apiVersion: v1
kind: ConfigMap
metadata:
  name: "example-config"
data:
  apiBaseUrl: "http://localhost:8090/api"
---
apiVersion: v1
kind: Secret
metadata:
  name: "example-secret"
data:
  apiKey: "c2VjcmV0"
