apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  containers:
    - name: echo-server
      image: ealen/echo-server
      envFrom:
        - secretRef:
            name: echo-server-secrets
      env:
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: echo-server-secrets
              key: api-secret
      ports:
        - name: http
          containerPort: 80
