apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  containers:
    - name: echo-server
      image: ealen/echo-server
      envFrom:
        - configMapRef:
            name: echo-server-config
      env:
        - name: VERBOSITY
          valueFrom:
            configMapKeyRef:
              name: echo-server-config
              key: LOG_LEVEL
      ports:
        - name: http
          containerPort: 80
