apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  containers:
    - name: echo-server
      image: ealen/echo-server
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: scripts
          mountPath: /init.d/init.sh
          subPath: init.sh
  volumes:
    - name: scripts
      configMap:
        name: echo-server-scripts
        defaultMode: 0544
