apiVersion: v1
kind: Config
clusters:
  - name: cluster-1
    cluster:
      server: https://kubecluster.org:6443
      certificate-authority-data: |
        # CLUSTER_CA_CERTIFICATE
users:
  - name: user-1
    user:
      client-certificate-data: |
        # USER_CERTIFICATE
      client-key-data: |
        # USER_PRIVATE_KEY
contexts:
  - name: context-1
    context:
      cluster: cluster-1
      user: user-1
current-context: context-1
