apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tester
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
