apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tester
subjects:
  - kind: ServiceAccount
    name: test-controller
