apiVersion: v1
kind: Service
metadata:
  name: echo-server-node
spec:
  type: NodePort
  selector:
    app: echo-server
  ports:
    - name: http-service
      targetPort: http
      port: 8080
      nodePort: 30808
